version: '3.10'

services:
  auth_app:
    restart: always
    volumes:
      - ./auth_app:/code
    container_name: auth_app_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - practicum

  auth_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433"
    healthcheck:
      test: ["CMD-SHELL", "su postgres", "&&", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - practicum

  redis:
    image: 'redis:6.2.6'
    ports:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - practicum

  nginx:
    image: nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./nginx/html:/etc/nginx/html:ro
    ports:
      - "81:80"
    depends_on:
      auth_app:
        condition: service_started
    restart: always
    networks:
      - practicum

  jaeger:
    image: jaegertracing/all-in-one:1.28
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
      - "6831:6831/udp" # Jaeger agent
      - "5778:5778"     # Jaeger admin port
    networks:
      - practicum

volumes:
  postgres_data:

networks:
  practicum:
    external: true
